# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feederwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLE = QtWidgets.QLineEdit(self.centralwidget)
        self.leftLE.setEnabled(True)
        self.leftLE.setReadOnly(True)
        self.leftLE.setObjectName("leftLE")
        self.horizontalLayout.addWidget(self.leftLE)
        self.leftLoadPB = QtWidgets.QPushButton(self.centralwidget)
        self.leftLoadPB.setObjectName("leftLoadPB")
        self.horizontalLayout.addWidget(self.leftLoadPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidgetLeft = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetLeft.setColumnCount(4)
        self.tableWidgetLeft.setObjectName("tableWidgetLeft")
        self.tableWidgetLeft.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidgetLeft)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftDeletePB = QtWidgets.QPushButton(self.centralwidget)
        self.leftDeletePB.setObjectName("leftDeletePB")
        self.horizontalLayout_4.addWidget(self.leftDeletePB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.LeftCopyPB = QtWidgets.QPushButton(self.centralwidget)
        self.LeftCopyPB.setObjectName("LeftCopyPB")
        self.horizontalLayout_4.addWidget(self.LeftCopyPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.copyLeftCB = QtWidgets.QCheckBox(self.centralwidget)
        self.copyLeftCB.setChecked(True)
        self.copyLeftCB.setObjectName("copyLeftCB")
        self.horizontalLayout_6.addWidget(self.copyLeftCB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rightLE = QtWidgets.QLineEdit(self.centralwidget)
        self.rightLE.setEnabled(True)
        self.rightLE.setReadOnly(True)
        self.rightLE.setObjectName("rightLE")
        self.horizontalLayout_2.addWidget(self.rightLE)
        self.rightLoadPB = QtWidgets.QPushButton(self.centralwidget)
        self.rightLoadPB.setObjectName("rightLoadPB")
        self.horizontalLayout_2.addWidget(self.rightLoadPB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidgetRight = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetRight.setColumnCount(4)
        self.tableWidgetRight.setObjectName("tableWidgetRight")
        self.tableWidgetRight.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidgetRight)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rightCopyPB = QtWidgets.QPushButton(self.centralwidget)
        self.rightCopyPB.setObjectName("rightCopyPB")
        self.horizontalLayout_3.addWidget(self.rightCopyPB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.rightDeletePB = QtWidgets.QPushButton(self.centralwidget)
        self.rightDeletePB.setObjectName("rightDeletePB")
        self.horizontalLayout_3.addWidget(self.rightDeletePB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.copyRightCB = QtWidgets.QCheckBox(self.centralwidget)
        self.copyRightCB.setChecked(True)
        self.copyRightCB.setObjectName("copyRightCB")
        self.horizontalLayout_7.addWidget(self.copyRightCB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.saveQuitPB = QtWidgets.QPushButton(self.centralwidget)
        self.saveQuitPB.setObjectName("saveQuitPB")
        self.horizontalLayout_5.addWidget(self.saveQuitPB)
        self.quitPB = QtWidgets.QPushButton(self.centralwidget)
        self.quitPB.setObjectName("quitPB")
        self.horizontalLayout_5.addWidget(self.quitPB)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 756, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.leftLoadPB.clicked.connect(MainWindow.loadLeft)
        self.rightLoadPB.clicked.connect(MainWindow.loadRight)
        self.leftDeletePB.clicked.connect(MainWindow.deleteLeft)
        self.rightDeletePB.clicked.connect(MainWindow.deleteRight)
        self.LeftCopyPB.clicked.connect(MainWindow.copyLeft)
        self.rightCopyPB.clicked.connect(MainWindow.copyRight)
        self.saveQuitPB.clicked.connect(MainWindow.saveQuit)
        self.quitPB.clicked.connect(MainWindow.quit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenPnp Feeder Management"))
        self.leftLoadPB.setText(_translate("MainWindow", "Load file"))
        self.leftDeletePB.setText(_translate("MainWindow", "Delete selected"))
        self.LeftCopyPB.setText(_translate("MainWindow", "Copy >>"))
        self.copyLeftCB.setText(_translate("MainWindow", "Make copy when updating"))
        self.rightLoadPB.setText(_translate("MainWindow", "Load file"))
        self.rightCopyPB.setText(_translate("MainWindow", "<< Copy"))
        self.rightDeletePB.setText(_translate("MainWindow", "Delete selected"))
        self.copyRightCB.setText(_translate("MainWindow", "Make copy when updating"))
        self.saveQuitPB.setText(_translate("MainWindow", "Save and Quit"))
        self.quitPB.setText(_translate("MainWindow", "Quit (no save)"))

