# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogplayground.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPlayground(object):
    def setupUi(self, DialogPlayground):
        DialogPlayground.setObjectName("DialogPlayground")
        DialogPlayground.resize(674, 682)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogPlayground)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabPlayground = QtWidgets.QTabWidget(DialogPlayground)
        self.tabPlayground.setObjectName("tabPlayground")
        self.tabBase = QtWidgets.QWidget()
        self.tabBase.setObjectName("tabBase")
        self.gridLayout = QtWidgets.QGridLayout(self.tabBase)
        self.gridLayout.setObjectName("gridLayout")
        self.camCBX = QtWidgets.QComboBox(self.tabBase)
        self.camCBX.setObjectName("camCBX")
        self.camCBX.addItem("")
        self.camCBX.addItem("")
        self.camCBX.addItem("")
        self.gridLayout.addWidget(self.camCBX, 5, 1, 1, 2)
        self.w3CB = QtWidgets.QCheckBox(self.tabBase)
        self.w3CB.setObjectName("w3CB")
        self.gridLayout.addWidget(self.w3CB, 1, 7, 1, 1)
        self.Z12CB = QtWidgets.QCheckBox(self.tabBase)
        self.Z12CB.setObjectName("Z12CB")
        self.gridLayout.addWidget(self.Z12CB, 1, 3, 1, 1)
        self.cameraButton = QtWidgets.QPushButton(self.tabBase)
        self.cameraButton.setObjectName("cameraButton")
        self.gridLayout.addWidget(self.cameraButton, 5, 0, 1, 1)
        self.speedSX = QtWidgets.QSpinBox(self.tabBase)
        self.speedSX.setMaximum(255)
        self.speedSX.setProperty("value", 127)
        self.speedSX.setObjectName("speedSX")
        self.gridLayout.addWidget(self.speedSX, 6, 1, 1, 1)
        self.xCB = QtWidgets.QCheckBox(self.tabBase)
        self.xCB.setObjectName("xCB")
        self.gridLayout.addWidget(self.xCB, 1, 1, 1, 1)
        self.resetValueCBX = QtWidgets.QComboBox(self.tabBase)
        self.resetValueCBX.setObjectName("resetValueCBX")
        self.resetValueCBX.addItem("")
        self.resetValueCBX.addItem("")
        self.resetValueCBX.addItem("")
        self.resetValueCBX.addItem("")
        self.resetValueCBX.addItem("")
        self.gridLayout.addWidget(self.resetValueCBX, 2, 1, 1, 2)
        self.resetValvesButton = QtWidgets.QPushButton(self.tabBase)
        self.resetValvesButton.setObjectName("resetValvesButton")
        self.gridLayout.addWidget(self.resetValvesButton, 2, 0, 1, 1)
        self.w2CB = QtWidgets.QCheckBox(self.tabBase)
        self.w2CB.setObjectName("w2CB")
        self.gridLayout.addWidget(self.w2CB, 1, 6, 1, 1)
        self.SpeedCoeffButton = QtWidgets.QPushButton(self.tabBase)
        self.SpeedCoeffButton.setObjectName("SpeedCoeffButton")
        self.gridLayout.addWidget(self.SpeedCoeffButton, 6, 0, 1, 1)
        self.readVacuumButton = QtWidgets.QPushButton(self.tabBase)
        self.readVacuumButton.setObjectName("readVacuumButton")
        self.gridLayout.addWidget(self.readVacuumButton, 7, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.tabBase)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 1, 0, 1, 1)
        self.w1CB = QtWidgets.QCheckBox(self.tabBase)
        self.w1CB.setObjectName("w1CB")
        self.gridLayout.addWidget(self.w1CB, 1, 5, 1, 1)
        self.onlineButton = QtWidgets.QPushButton(self.tabBase)
        self.onlineButton.setObjectName("onlineButton")
        self.gridLayout.addWidget(self.onlineButton, 0, 0, 1, 1)
        self.solenoidButton = QtWidgets.QPushButton(self.tabBase)
        self.solenoidButton.setObjectName("solenoidButton")
        self.gridLayout.addWidget(self.solenoidButton, 3, 0, 1, 1)
        self.readVacuumCBX = QtWidgets.QComboBox(self.tabBase)
        self.readVacuumCBX.setObjectName("readVacuumCBX")
        self.readVacuumCBX.addItem("")
        self.readVacuumCBX.addItem("")
        self.readVacuumCBX.addItem("")
        self.readVacuumCBX.addItem("")
        self.gridLayout.addWidget(self.readVacuumCBX, 7, 1, 1, 2)
        self.brightnessSX = QtWidgets.QSpinBox(self.tabBase)
        self.brightnessSX.setMaximum(255)
        self.brightnessSX.setProperty("value", 127)
        self.brightnessSX.setObjectName("brightnessSX")
        self.gridLayout.addWidget(self.brightnessSX, 5, 4, 1, 1)
        self.z34CB = QtWidgets.QCheckBox(self.tabBase)
        self.z34CB.setObjectName("z34CB")
        self.gridLayout.addWidget(self.z34CB, 1, 4, 1, 1)
        self.yCB = QtWidgets.QCheckBox(self.tabBase)
        self.yCB.setObjectName("yCB")
        self.gridLayout.addWidget(self.yCB, 1, 2, 1, 1)
        self.rasetValveRawSB = QtWidgets.QSpinBox(self.tabBase)
        self.rasetValveRawSB.setObjectName("rasetValveRawSB")
        self.gridLayout.addWidget(self.rasetValveRawSB, 2, 3, 1, 1)
        self.solenoidCBX = QtWidgets.QComboBox(self.tabBase)
        self.solenoidCBX.setObjectName("solenoidCBX")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.solenoidCBX.addItem("")
        self.gridLayout.addWidget(self.solenoidCBX, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.tabBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 3, 1, 1)
        self.solenoidSB = QtWidgets.QSpinBox(self.tabBase)
        self.solenoidSB.setObjectName("solenoidSB")
        self.gridLayout.addWidget(self.solenoidSB, 3, 3, 1, 1)
        self.smtModeButton = QtWidgets.QPushButton(self.tabBase)
        self.smtModeButton.setObjectName("smtModeButton")
        self.gridLayout.addWidget(self.smtModeButton, 8, 0, 1, 1)
        self.smtModeCBX = QtWidgets.QComboBox(self.tabBase)
        self.smtModeCBX.setObjectName("smtModeCBX")
        self.smtModeCBX.addItem("")
        self.smtModeCBX.addItem("")
        self.smtModeCBX.addItem("")
        self.smtModeCBX.addItem("")
        self.smtModeCBX.addItem("")
        self.gridLayout.addWidget(self.smtModeCBX, 8, 1, 1, 2)
        self.solenoidEnableCB = QtWidgets.QCheckBox(self.tabBase)
        self.solenoidEnableCB.setObjectName("solenoidEnableCB")
        self.gridLayout.addWidget(self.solenoidEnableCB, 3, 4, 1, 1)
        self.tabPlayground.addTab(self.tabBase, "")
        self.tabMove = QtWidgets.QWidget()
        self.tabMove.setObjectName("tabMove")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabMove)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tabMove)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.moveSteps = QtWidgets.QSpinBox(self.tabMove)
        self.moveSteps.setMinimum(-1000000)
        self.moveSteps.setMaximum(1000000)
        self.moveSteps.setObjectName("moveSteps")
        self.horizontalLayout_2.addWidget(self.moveSteps)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tabMove)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.moveStartSpeed = QtWidgets.QSpinBox(self.tabMove)
        self.moveStartSpeed.setMaximum(255)
        self.moveStartSpeed.setObjectName("moveStartSpeed")
        self.horizontalLayout.addWidget(self.moveStartSpeed)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tabMove)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.moveRunSpeed = QtWidgets.QSpinBox(self.tabMove)
        self.moveRunSpeed.setMaximum(255)
        self.moveRunSpeed.setObjectName("moveRunSpeed")
        self.horizontalLayout_3.addWidget(self.moveRunSpeed)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.moveButton = QtWidgets.QPushButton(self.tabMove)
        self.moveButton.setObjectName("moveButton")
        self.verticalLayout_3.addWidget(self.moveButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.moveAxesGB = QtWidgets.QGroupBox(self.tabMove)
        self.moveAxesGB.setObjectName("moveAxesGB")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.moveAxesGB)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rb7 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb7.setObjectName("rb7")
        self.buttonGroup = QtWidgets.QButtonGroup(DialogPlayground)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb7)
        self.gridLayout_3.addWidget(self.rb7, 7, 0, 1, 1)
        self.rb6 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb6.setObjectName("rb6")
        self.buttonGroup.addButton(self.rb6)
        self.gridLayout_3.addWidget(self.rb6, 6, 0, 1, 1)
        self.rb2 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb2.setObjectName("rb2")
        self.buttonGroup.addButton(self.rb2)
        self.gridLayout_3.addWidget(self.rb2, 2, 0, 1, 1)
        self.rb10 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb10.setObjectName("rb10")
        self.buttonGroup.addButton(self.rb10)
        self.gridLayout_3.addWidget(self.rb10, 10, 0, 1, 1)
        self.rb9 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb9.setObjectName("rb9")
        self.buttonGroup.addButton(self.rb9)
        self.gridLayout_3.addWidget(self.rb9, 9, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_3.addWidget(self.radioButton_2, 12, 0, 1, 1)
        self.rb8 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb8.setObjectName("rb8")
        self.buttonGroup.addButton(self.rb8)
        self.gridLayout_3.addWidget(self.rb8, 8, 0, 1, 1)
        self.rb1 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb1.setChecked(True)
        self.rb1.setObjectName("rb1")
        self.buttonGroup.addButton(self.rb1)
        self.gridLayout_3.addWidget(self.rb1, 0, 0, 1, 1)
        self.rb3 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb3.setObjectName("rb3")
        self.buttonGroup.addButton(self.rb3)
        self.gridLayout_3.addWidget(self.rb3, 3, 0, 1, 1)
        self.rb5 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb5.setObjectName("rb5")
        self.buttonGroup.addButton(self.rb5)
        self.gridLayout_3.addWidget(self.rb5, 5, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout_3.addWidget(self.radioButton_3, 13, 0, 1, 1)
        self.rb4 = QtWidgets.QRadioButton(self.moveAxesGB)
        self.rb4.setObjectName("rb4")
        self.buttonGroup.addButton(self.rb4)
        self.gridLayout_3.addWidget(self.rb4, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.moveAxesGB)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_3.addWidget(self.radioButton, 14, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.moveAxesGB)
        self.tabPlayground.addTab(self.tabMove, "")
        self.tabHeadMove = QtWidgets.QWidget()
        self.tabHeadMove.setObjectName("tabHeadMove")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabHeadMove)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hmRsY = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmRsY.setMaximum(255)
        self.hmRsY.setObjectName("hmRsY")
        self.gridLayout_2.addWidget(self.hmRsY, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.hmRsA3 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmRsA3.setMaximum(255)
        self.hmRsA3.setObjectName("hmRsA3")
        self.gridLayout_2.addWidget(self.hmRsA3, 7, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.hmRsX = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmRsX.setMaximum(255)
        self.hmRsX.setObjectName("hmRsX")
        self.gridLayout_2.addWidget(self.hmRsX, 3, 3, 1, 1)
        self.hmSsY = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmSsY.setMaximum(255)
        self.hmSsY.setObjectName("hmSsY")
        self.gridLayout_2.addWidget(self.hmSsY, 4, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.HeadMoveButton = QtWidgets.QPushButton(self.tabHeadMove)
        self.HeadMoveButton.setObjectName("HeadMoveButton")
        self.gridLayout_2.addWidget(self.HeadMoveButton, 9, 0, 1, 1)
        self.hmStepsA2 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmStepsA2.setMinimum(-1000000)
        self.hmStepsA2.setMaximum(1000000)
        self.hmStepsA2.setObjectName("hmStepsA2")
        self.gridLayout_2.addWidget(self.hmStepsA2, 6, 1, 1, 1)
        self.hmRsA4 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmRsA4.setMaximum(255)
        self.hmRsA4.setObjectName("hmRsA4")
        self.gridLayout_2.addWidget(self.hmRsA4, 8, 3, 1, 1)
        self.hmSsX = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmSsX.setMaximum(255)
        self.hmSsX.setObjectName("hmSsX")
        self.gridLayout_2.addWidget(self.hmSsX, 3, 2, 1, 1)
        self.hmSsA4 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmSsA4.setMaximum(255)
        self.hmSsA4.setObjectName("hmSsA4")
        self.gridLayout_2.addWidget(self.hmSsA4, 8, 2, 1, 1)
        self.hmStepsY = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmStepsY.setMinimum(-1000000)
        self.hmStepsY.setMaximum(1000000)
        self.hmStepsY.setObjectName("hmStepsY")
        self.gridLayout_2.addWidget(self.hmStepsY, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.hmRsA2 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmRsA2.setMaximum(255)
        self.hmRsA2.setObjectName("hmRsA2")
        self.gridLayout_2.addWidget(self.hmRsA2, 6, 3, 1, 1)
        self.hmSsA1 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmSsA1.setMaximum(255)
        self.hmSsA1.setObjectName("hmSsA1")
        self.gridLayout_2.addWidget(self.hmSsA1, 5, 2, 1, 1)
        self.hmStepsA3 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmStepsA3.setMinimum(-1000000)
        self.hmStepsA3.setMaximum(1000000)
        self.hmStepsA3.setObjectName("hmStepsA3")
        self.gridLayout_2.addWidget(self.hmStepsA3, 7, 1, 1, 1)
        self.hmStepsA1 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmStepsA1.setMinimum(-1000000)
        self.hmStepsA1.setMaximum(1000000)
        self.hmStepsA1.setObjectName("hmStepsA1")
        self.gridLayout_2.addWidget(self.hmStepsA1, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.hmStepsX = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmStepsX.setMinimum(-1000000)
        self.hmStepsX.setMaximum(1000000)
        self.hmStepsX.setObjectName("hmStepsX")
        self.gridLayout_2.addWidget(self.hmStepsX, 3, 1, 1, 1)
        self.hmStepsA4 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmStepsA4.setMinimum(-1000000)
        self.hmStepsA4.setMaximum(1000000)
        self.hmStepsA4.setObjectName("hmStepsA4")
        self.gridLayout_2.addWidget(self.hmStepsA4, 8, 1, 1, 1)
        self.hmRsA1 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmRsA1.setMaximum(255)
        self.hmRsA1.setObjectName("hmRsA1")
        self.gridLayout_2.addWidget(self.hmRsA1, 5, 3, 1, 1)
        self.hmSsA2 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmSsA2.setMaximum(255)
        self.hmSsA2.setObjectName("hmSsA2")
        self.gridLayout_2.addWidget(self.hmSsA2, 6, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tabHeadMove)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        self.hmSsA3 = QtWidgets.QSpinBox(self.tabHeadMove)
        self.hmSsA3.setMaximum(255)
        self.hmSsA3.setObjectName("hmSsA3")
        self.gridLayout_2.addWidget(self.hmSsA3, 7, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.waitCB = QtWidgets.QCheckBox(self.tabHeadMove)
        self.waitCB.setObjectName("waitCB")
        self.gridLayout_2.addWidget(self.waitCB, 9, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setColumnStretch(2, 4)
        self.gridLayout_2.setColumnStretch(3, 4)
        self.tabPlayground.addTab(self.tabHeadMove, "")
        self.tabFeeders = QtWidgets.QWidget()
        self.tabFeeders.setObjectName("tabFeeders")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabFeeders)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.tabFeeders)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 4, 1, 1, 1)
        self.feedersCBX = QtWidgets.QComboBox(self.tabFeeders)
        self.feedersCBX.setObjectName("feedersCBX")
        self.feedersCBX.addItem("")
        self.feedersCBX.addItem("")
        self.feedersCBX.addItem("")
        self.gridLayout_4.addWidget(self.feedersCBX, 0, 1, 1, 1)
        self.fOl = QtWidgets.QSpinBox(self.tabFeeders)
        self.fOl.setMaximum(65535)
        self.fOl.setObjectName("fOl")
        self.gridLayout_4.addWidget(self.fOl, 4, 2, 1, 1)
        self.feederButton = QtWidgets.QPushButton(self.tabFeeders)
        self.feederButton.setObjectName("feederButton")
        self.gridLayout_4.addWidget(self.feederButton, 0, 0, 1, 1)
        self.fRs = QtWidgets.QSpinBox(self.tabFeeders)
        self.fRs.setMaximum(255)
        self.fRs.setObjectName("fRs")
        self.gridLayout_4.addWidget(self.fRs, 3, 2, 1, 1)
        self.flast = QtWidgets.QSpinBox(self.tabFeeders)
        self.flast.setMaximum(255)
        self.flast.setProperty("value", 1)
        self.flast.setObjectName("flast")
        self.gridLayout_4.addWidget(self.flast, 10, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tabFeeders)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 8, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tabFeeders)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 12, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tabFeeders)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 1, 1, 1)
        self.fFt = QtWidgets.QSpinBox(self.tabFeeders)
        self.fFt.setMaximum(65535)
        self.fFt.setObjectName("fFt")
        self.gridLayout_4.addWidget(self.fFt, 8, 2, 1, 1)
        self.ocRs = QtWidgets.QSpinBox(self.tabFeeders)
        self.ocRs.setMaximum(255)
        self.ocRs.setObjectName("ocRs")
        self.gridLayout_4.addWidget(self.ocRs, 7, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tabFeeders)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 7, 1, 1, 1)
        self.fCl = QtWidgets.QSpinBox(self.tabFeeders)
        self.fCl.setMaximum(65535)
        self.fCl.setObjectName("fCl")
        self.gridLayout_4.addWidget(self.fCl, 5, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tabFeeders)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tabFeeders)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 6, 1, 1, 1)
        self.ocSs = QtWidgets.QSpinBox(self.tabFeeders)
        self.ocSs.setMaximum(255)
        self.ocSs.setObjectName("ocSs")
        self.gridLayout_4.addWidget(self.ocSs, 6, 2, 1, 1)
        self.fCli = QtWidgets.QSpinBox(self.tabFeeders)
        self.fCli.setMaximum(255)
        self.fCli.setObjectName("fCli")
        self.gridLayout_4.addWidget(self.fCli, 11, 2, 1, 1)
        self.fClt = QtWidgets.QSpinBox(self.tabFeeders)
        self.fClt.setMaximum(65535)
        self.fClt.setObjectName("fClt")
        self.gridLayout_4.addWidget(self.fClt, 12, 2, 1, 1)
        self.fSteps = QtWidgets.QSpinBox(self.tabFeeders)
        self.fSteps.setMinimum(-1000000)
        self.fSteps.setMaximum(1000000)
        self.fSteps.setObjectName("fSteps")
        self.gridLayout_4.addWidget(self.fSteps, 1, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tabFeeders)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 11, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tabFeeders)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 9, 1, 1, 1)
        self.yamahaFeederButton = QtWidgets.QPushButton(self.tabFeeders)
        self.yamahaFeederButton.setObjectName("yamahaFeederButton")
        self.gridLayout_4.addWidget(self.yamahaFeederButton, 11, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tabFeeders)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tabFeeders)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tabFeeders)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 10, 1, 1, 1)
        self.fPc = QtWidgets.QSpinBox(self.tabFeeders)
        self.fPc.setMaximum(255)
        self.fPc.setProperty("value", 1)
        self.fPc.setObjectName("fPc")
        self.gridLayout_4.addWidget(self.fPc, 9, 2, 1, 1)
        self.fSs = QtWidgets.QSpinBox(self.tabFeeders)
        self.fSs.setMinimum(-1000000)
        self.fSs.setMaximum(1000000)
        self.fSs.setObjectName("fSs")
        self.gridLayout_4.addWidget(self.fSs, 2, 2, 1, 1)
        self.tabPlayground.addTab(self.tabFeeders, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.piN = QtWidgets.QSpinBox(self.tab)
        self.piN.setMaximum(255)
        self.piN.setObjectName("piN")
        self.gridLayout_5.addWidget(self.piN, 5, 2, 1, 1)
        self.placeButton = QtWidgets.QPushButton(self.tab)
        self.placeButton.setObjectName("placeButton")
        self.gridLayout_5.addWidget(self.placeButton, 9, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 12, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 13, 1, 1, 1)
        self.piSs = QtWidgets.QSpinBox(self.tab)
        self.piSs.setMaximum(255)
        self.piSs.setObjectName("piSs")
        self.gridLayout_5.addWidget(self.piSs, 3, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 7, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 5, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 4, 1, 1, 1)
        self.placeAxeCBX = QtWidgets.QComboBox(self.tab)
        self.placeAxeCBX.setObjectName("placeAxeCBX")
        self.placeAxeCBX.addItem("")
        self.placeAxeCBX.addItem("")
        self.placeAxeCBX.addItem("")
        self.placeAxeCBX.addItem("")
        self.gridLayout_5.addWidget(self.placeAxeCBX, 9, 1, 1, 1)
        self.piRs = QtWidgets.QSpinBox(self.tab)
        self.piRs.setMaximum(255)
        self.piRs.setObjectName("piRs")
        self.gridLayout_5.addWidget(self.piRs, 4, 2, 1, 1)
        self.pickButton = QtWidgets.QPushButton(self.tab)
        self.pickButton.setObjectName("pickButton")
        self.gridLayout_5.addWidget(self.pickButton, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 10, 1, 1, 1)
        self.pickAxeCBX = QtWidgets.QComboBox(self.tab)
        self.pickAxeCBX.setObjectName("pickAxeCBX")
        self.pickAxeCBX.addItem("")
        self.pickAxeCBX.addItem("")
        self.pickAxeCBX.addItem("")
        self.pickAxeCBX.addItem("")
        self.gridLayout_5.addWidget(self.pickAxeCBX, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 11, 1, 1, 1)
        self.piVtl = QtWidgets.QSpinBox(self.tab)
        self.piVtl.setMaximum(255)
        self.piVtl.setObjectName("piVtl")
        self.gridLayout_5.addWidget(self.piVtl, 7, 2, 1, 1)
        self.piPd = QtWidgets.QSpinBox(self.tab)
        self.piPd.setMaximum(65535)
        self.piPd.setObjectName("piPd")
        self.gridLayout_5.addWidget(self.piPd, 6, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 14, 1, 1, 1)
        self.piZ = QtWidgets.QSpinBox(self.tab)
        self.piZ.setMinimum(-1000000)
        self.piZ.setMaximum(1000000)
        self.piZ.setObjectName("piZ")
        self.gridLayout_5.addWidget(self.piZ, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 6, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 15, 1, 1, 1)
        self.plZ = QtWidgets.QSpinBox(self.tab)
        self.plZ.setMinimum(-1000000)
        self.plZ.setMaximum(1000000)
        self.plZ.setObjectName("plZ")
        self.gridLayout_5.addWidget(self.plZ, 10, 2, 1, 1)
        self.plSs = QtWidgets.QSpinBox(self.tab)
        self.plSs.setMaximum(255)
        self.plSs.setObjectName("plSs")
        self.gridLayout_5.addWidget(self.plSs, 11, 2, 1, 1)
        self.plRs = QtWidgets.QSpinBox(self.tab)
        self.plRs.setMaximum(255)
        self.plRs.setObjectName("plRs")
        self.gridLayout_5.addWidget(self.plRs, 12, 2, 1, 1)
        self.plZsvs = QtWidgets.QSpinBox(self.tab)
        self.plZsvs.setMinimum(-1000000)
        self.plZsvs.setMaximum(1000000)
        self.plZsvs.setObjectName("plZsvs")
        self.gridLayout_5.addWidget(self.plZsvs, 13, 2, 1, 1)
        self.plPd = QtWidgets.QSpinBox(self.tab)
        self.plPd.setMaximum(65535)
        self.plPd.setObjectName("plPd")
        self.gridLayout_5.addWidget(self.plPd, 14, 2, 1, 1)
        self.plVtl = QtWidgets.QSpinBox(self.tab)
        self.plVtl.setMaximum(255)
        self.plVtl.setObjectName("plVtl")
        self.gridLayout_5.addWidget(self.plVtl, 15, 2, 1, 1)
        self.tabPlayground.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabPlayground)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_40 = QtWidgets.QLabel(DialogPlayground)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_7.addWidget(self.label_40)
        self.frameOutLE = QtWidgets.QLineEdit(DialogPlayground)
        self.frameOutLE.setObjectName("frameOutLE")
        self.horizontalLayout_7.addWidget(self.frameOutLE)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_39 = QtWidgets.QLabel(DialogPlayground)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_6.addWidget(self.label_39)
        self.frameInLE = QtWidgets.QLineEdit(DialogPlayground)
        self.frameInLE.setObjectName("frameInLE")
        self.horizontalLayout_6.addWidget(self.frameInLE)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(DialogPlayground)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPlayground)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogPlayground)
        self.tabPlayground.setCurrentIndex(3)
        self.buttonBox.accepted.connect(DialogPlayground.accept)
        self.buttonBox.rejected.connect(DialogPlayground.reject)
        self.onlineButton.clicked.connect(DialogPlayground.pbBaseOnline)
        self.resetButton.clicked.connect(DialogPlayground.pbBaseReset)
        self.resetValvesButton.clicked.connect(DialogPlayground.pbBaseResetValves)
        self.solenoidButton.clicked.connect(DialogPlayground.pbBaseSolenoid)
        self.cameraButton.clicked.connect(DialogPlayground.pbBaseCamera)
        self.SpeedCoeffButton.clicked.connect(DialogPlayground.pbBaseSpeedCoeff)
        self.readVacuumButton.clicked.connect(DialogPlayground.pbBaseReadVacuum)
        self.smtModeButton.clicked.connect(DialogPlayground.pbBaseSmtMode)
        self.moveButton.clicked.connect(DialogPlayground.pbMoveAxis)
        self.HeadMoveButton.clicked.connect(DialogPlayground.pbHeadMove)
        self.feederButton.clicked.connect(DialogPlayground.pbFeeder)
        self.yamahaFeederButton.clicked.connect(DialogPlayground.pbClFeeder)
        self.pickButton.clicked.connect(DialogPlayground.pbPick)
        self.placeButton.clicked.connect(DialogPlayground.pbPlace)
        QtCore.QMetaObject.connectSlotsByName(DialogPlayground)

    def retranslateUi(self, DialogPlayground):
        _translate = QtCore.QCoreApplication.translate
        DialogPlayground.setWindowTitle(_translate("DialogPlayground", "Playground"))
        self.camCBX.setItemText(0, _translate("DialogPlayground", "0x01 CAM_DOWN"))
        self.camCBX.setItemText(1, _translate("DialogPlayground", "0x02 CAM_UP_LEFT"))
        self.camCBX.setItemText(2, _translate("DialogPlayground", "0x03 CAM_UP_RIGHT"))
        self.w3CB.setText(_translate("DialogPlayground", "W3"))
        self.Z12CB.setText(_translate("DialogPlayground", "Z1/2"))
        self.cameraButton.setText(_translate("DialogPlayground", "Camera"))
        self.xCB.setText(_translate("DialogPlayground", "X"))
        self.resetValueCBX.setItemText(0, _translate("DialogPlayground", "use raw value"))
        self.resetValueCBX.setItemText(1, _translate("DialogPlayground", "0x06 VALVE_NFEEDER"))
        self.resetValueCBX.setItemText(2, _translate("DialogPlayground", "0x05 VALVE_WFEEDER"))
        self.resetValueCBX.setItemText(3, _translate("DialogPlayground", "0x07 VALVE_EFEEDER"))
        self.resetValueCBX.setItemText(4, _translate("DialogPlayground", "0x0A VALVE_SFEEDER"))
        self.resetValvesButton.setText(_translate("DialogPlayground", "Reset Valves"))
        self.w2CB.setText(_translate("DialogPlayground", "W2"))
        self.SpeedCoeffButton.setText(_translate("DialogPlayground", "SpeedCoeff"))
        self.readVacuumButton.setText(_translate("DialogPlayground", "Read Vacuum"))
        self.resetButton.setText(_translate("DialogPlayground", "Reset"))
        self.w1CB.setText(_translate("DialogPlayground", "W1"))
        self.onlineButton.setText(_translate("DialogPlayground", "Online"))
        self.solenoidButton.setText(_translate("DialogPlayground", "Solenoid"))
        self.readVacuumCBX.setItemText(0, _translate("DialogPlayground", "0x01 NOZZLE1"))
        self.readVacuumCBX.setItemText(1, _translate("DialogPlayground", "0x02 NOZZLE2"))
        self.readVacuumCBX.setItemText(2, _translate("DialogPlayground", "0x03 NOZZLE3"))
        self.readVacuumCBX.setItemText(3, _translate("DialogPlayground", "0x04 NOZZLE4"))
        self.z34CB.setText(_translate("DialogPlayground", "Z2/3"))
        self.yCB.setText(_translate("DialogPlayground", "Y"))
        self.solenoidCBX.setItemText(0, _translate("DialogPlayground", "use raw value"))
        self.solenoidCBX.setItemText(1, _translate("DialogPlayground", "0x01 VACUUM1"))
        self.solenoidCBX.setItemText(2, _translate("DialogPlayground", "0x02 VACUUM2"))
        self.solenoidCBX.setItemText(3, _translate("DialogPlayground", "0x03 VACUUM3"))
        self.solenoidCBX.setItemText(4, _translate("DialogPlayground", "0x04 VACUUM4"))
        self.solenoidCBX.setItemText(5, _translate("DialogPlayground", "0x05 WEST_FEEDER"))
        self.solenoidCBX.setItemText(6, _translate("DialogPlayground", "0x06 NORTH_FEEDER"))
        self.solenoidCBX.setItemText(7, _translate("DialogPlayground", "0x07 EAST_FEEDER"))
        self.solenoidCBX.setItemText(8, _translate("DialogPlayground", "0x0A VIBRATION"))
        self.solenoidCBX.setItemText(9, _translate("DialogPlayground", "0x0B LIGHT1"))
        self.solenoidCBX.setItemText(10, _translate("DialogPlayground", "0x0C LIGHT2"))
        self.solenoidCBX.setItemText(11, _translate("DialogPlayground", "0x0D LIGHT3"))
        self.label.setText(_translate("DialogPlayground", "Brightness(B)"))
        self.smtModeButton.setText(_translate("DialogPlayground", "SMT Mode"))
        self.smtModeCBX.setItemText(0, _translate("DialogPlayground", "0x00 MANUAL"))
        self.smtModeCBX.setItemText(1, _translate("DialogPlayground", "0x01 BEGIN"))
        self.smtModeCBX.setItemText(2, _translate("DialogPlayground", "0x02 PAUSE"))
        self.smtModeCBX.setItemText(3, _translate("DialogPlayground", "0x03 RECOVER"))
        self.smtModeCBX.setItemText(4, _translate("DialogPlayground", "0x04 STOP"))
        self.solenoidEnableCB.setText(_translate("DialogPlayground", "Enable"))
        self.tabPlayground.setTabText(self.tabPlayground.indexOf(self.tabBase), _translate("DialogPlayground", "Base"))
        self.label_3.setText(_translate("DialogPlayground", "Steps"))
        self.label_2.setText(_translate("DialogPlayground", "Start Speed(B)"))
        self.label_4.setText(_translate("DialogPlayground", "Run Speed(B)"))
        self.moveButton.setText(_translate("DialogPlayground", "Move Axis"))
        self.moveAxesGB.setTitle(_translate("DialogPlayground", "Axes"))
        self.rb7.setText(_translate("DialogPlayground", "0x04 A1"))
        self.rb6.setText(_translate("DialogPlayground", "0x03 Z4"))
        self.rb2.setText(_translate("DialogPlayground", "0x01 Y"))
        self.rb10.setText(_translate("DialogPlayground", "0x07 A4"))
        self.rb9.setText(_translate("DialogPlayground", "0x06 A3"))
        self.radioButton_2.setText(_translate("DialogPlayground", "0x08 WEST_FEEDER"))
        self.rb8.setText(_translate("DialogPlayground", "0x05 A2"))
        self.rb1.setText(_translate("DialogPlayground", "0x00 X"))
        self.rb3.setText(_translate("DialogPlayground", "0x02 Z1"))
        self.rb5.setText(_translate("DialogPlayground", "0x03 Z3"))
        self.radioButton_3.setText(_translate("DialogPlayground", "0x09 NORTH_FEEDER"))
        self.rb4.setText(_translate("DialogPlayground", "0x02 Z2"))
        self.radioButton.setText(_translate("DialogPlayground", "0x0A EAST_FEEDER"))
        self.tabPlayground.setTabText(self.tabPlayground.indexOf(self.tabMove), _translate("DialogPlayground", "Move"))
        self.label_7.setText(_translate("DialogPlayground", "A1"))
        self.label_11.setText(_translate("DialogPlayground", "Axis"))
        self.label_13.setText(_translate("DialogPlayground", "Start Speed (B)"))
        self.label_10.setText(_translate("DialogPlayground", "A4"))
        self.HeadMoveButton.setText(_translate("DialogPlayground", "Move Head"))
        self.label_5.setText(_translate("DialogPlayground", "X"))
        self.label_6.setText(_translate("DialogPlayground", "Y"))
        self.label_14.setText(_translate("DialogPlayground", "Run Speed (B)"))
        self.label_9.setText(_translate("DialogPlayground", "A3"))
        self.label_8.setText(_translate("DialogPlayground", "A2"))
        self.label_12.setText(_translate("DialogPlayground", "Steps"))
        self.waitCB.setText(_translate("DialogPlayground", "Return early"))
        self.tabPlayground.setTabText(self.tabPlayground.indexOf(self.tabHeadMove), _translate("DialogPlayground", "Head move"))
        self.label_18.setText(_translate("DialogPlayground", "Open Length (S)"))
        self.feedersCBX.setItemText(0, _translate("DialogPlayground", "0x01 WEST_FEEDER"))
        self.feedersCBX.setItemText(1, _translate("DialogPlayground", "0x02 NORTH_FEEDER"))
        self.feedersCBX.setItemText(2, _translate("DialogPlayground", "0x03 EAST_FEEDER"))
        self.feederButton.setText(_translate("DialogPlayground", "Feeder"))
        self.label_22.setText(_translate("DialogPlayground", "Feed time (S)"))
        self.label_26.setText(_translate("DialogPlayground", "Feed time [us]"))
        self.label_15.setText(_translate("DialogPlayground", "Steps"))
        self.label_21.setText(_translate("DialogPlayground", "Open Close Speed Run (B)"))
        self.label_16.setText(_translate("DialogPlayground", "Startup Speed (B)"))
        self.label_20.setText(_translate("DialogPlayground", "Open Close Speed Start (B)"))
        self.label_25.setText(_translate("DialogPlayground", "Feeder Index"))
        self.label_23.setText(_translate("DialogPlayground", "Push Cunt (B)"))
        self.yamahaFeederButton.setText(_translate("DialogPlayground", "CL Feeder"))
        self.label_19.setText(_translate("DialogPlayground", "Closed Length (S)"))
        self.label_17.setText(_translate("DialogPlayground", "Run Speed (B)"))
        self.label_24.setText(_translate("DialogPlayground", "?"))
        self.tabPlayground.setTabText(self.tabPlayground.indexOf(self.tabFeeders), _translate("DialogPlayground", "Feeders"))
        self.placeButton.setText(_translate("DialogPlayground", "Place"))
        self.label_35.setText(_translate("DialogPlayground", "Run SPeed (B)"))
        self.label_36.setText(_translate("DialogPlayground", "Z Steps Vacuum Shut"))
        self.label_29.setText(_translate("DialogPlayground", "Vacuum Test Level (B)"))
        self.label_30.setText(_translate("DialogPlayground", "Nozzle Nr (B)"))
        self.label_31.setText(_translate("DialogPlayground", "Run Speed (B)"))
        self.placeAxeCBX.setItemText(0, _translate("DialogPlayground", "0x02 Z1"))
        self.placeAxeCBX.setItemText(1, _translate("DialogPlayground", "0x02 Z2"))
        self.placeAxeCBX.setItemText(2, _translate("DialogPlayground", "0x03 Z3"))
        self.placeAxeCBX.setItemText(3, _translate("DialogPlayground", "0x04 Z4"))
        self.pickButton.setText(_translate("DialogPlayground", "Pick"))
        self.label_32.setText(_translate("DialogPlayground", "Start Speed (B)"))
        self.label_33.setText(_translate("DialogPlayground", "Z steps"))
        self.pickAxeCBX.setItemText(0, _translate("DialogPlayground", "0x02 Z1"))
        self.pickAxeCBX.setItemText(1, _translate("DialogPlayground", "0x02 Z2"))
        self.pickAxeCBX.setItemText(2, _translate("DialogPlayground", "0x03 Z3"))
        self.pickAxeCBX.setItemText(3, _translate("DialogPlayground", "0x03 Z4"))
        self.label_34.setText(_translate("DialogPlayground", "Start Speed (B)"))
        self.label_27.setText(_translate("DialogPlayground", "Z steps"))
        self.label_37.setText(_translate("DialogPlayground", "Put Delay (S)"))
        self.label_28.setText(_translate("DialogPlayground", "Put Delay (S)"))
        self.label_38.setText(_translate("DialogPlayground", "Vacuum Test Level (B)"))
        self.tabPlayground.setTabText(self.tabPlayground.indexOf(self.tab), _translate("DialogPlayground", "Pick&&Place"))
        self.label_40.setText(_translate("DialogPlayground", "Frame >"))
        self.label_39.setText(_translate("DialogPlayground", "Frame <"))

