# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonConnect.setAutoDefault(True)
        self.pushButtonConnect.setFlat(False)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayout.addWidget(self.pushButtonConnect, 1, 4, 1, 1)
        self.comboBoxSerialPorts = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxSerialPorts.setObjectName("comboBoxSerialPorts")
        self.gridLayout.addWidget(self.comboBoxSerialPorts, 1, 2, 1, 1)
        self.fnameLE = QtWidgets.QLineEdit(self.centralWidget)
        self.fnameLE.setObjectName("fnameLE")
        self.gridLayout.addWidget(self.fnameLE, 0, 2, 1, 1)
        self.machineTypesCB = QtWidgets.QComboBox(self.centralWidget)
        self.machineTypesCB.setObjectName("machineTypesCB")
        self.machineTypesCB.addItem("")
        self.machineTypesCB.addItem("")
        self.machineTypesCB.addItem("")
        self.machineTypesCB.addItem("")
        self.gridLayout.addWidget(self.machineTypesCB, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.selectConfgiPB = QtWidgets.QPushButton(self.centralWidget)
        self.selectConfgiPB.setObjectName("selectConfgiPB")
        self.gridLayout.addWidget(self.selectConfgiPB, 0, 1, 1, 1)
        self.refreshPortPB = QtWidgets.QPushButton(self.centralWidget)
        self.refreshPortPB.setObjectName("refreshPortPB")
        self.gridLayout.addWidget(self.refreshPortPB, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.loggerWindow = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.loggerWindow.setObjectName("loggerWindow")
        self.verticalLayout.addWidget(self.loggerWindow)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuConfiguration = QtWidgets.QMenu(self.menuBar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTesting = QtWidgets.QMenu(self.menuBar)
        self.menuTesting.setObjectName("menuTesting")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionGlobal_settings = QtWidgets.QAction(MainWindow)
        self.actionGlobal_settings.setObjectName("actionGlobal_settings")
        self.actionMachine_settings = QtWidgets.QAction(MainWindow)
        self.actionMachine_settings.setObjectName("actionMachine_settings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionPlayground = QtWidgets.QAction(MainWindow)
        self.actionPlayground.setObjectName("actionPlayground")
        self.actionReload_Settings_from_File = QtWidgets.QAction(MainWindow)
        self.actionReload_Settings_from_File.setObjectName("actionReload_Settings_from_File")
        self.menuConfiguration.addAction(self.actionGlobal_settings)
        self.menuConfiguration.addAction(self.actionMachine_settings)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.actionSave)
        self.menuConfiguration.addAction(self.actionReload_Settings_from_File)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTesting.addSeparator()
        self.menuTesting.addAction(self.actionPlayground)
        self.menuBar.addAction(self.menuConfiguration.menuAction())
        self.menuBar.addAction(self.menuTesting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButtonConnect.clicked.connect(MainWindow.enableComm)
        self.actionGlobal_settings.triggered.connect(MainWindow.configGlobal)
        self.actionMachine_settings.triggered.connect(MainWindow.configMachine)
        self.actionAbout.triggered.connect(MainWindow.about)
        self.selectConfgiPB.clicked.connect(MainWindow.selectConfig)
        self.refreshPortPB.clicked.connect(MainWindow.refreshPort)
        self.actionSave.triggered.connect(MainWindow.saveSettings)
        self.actionPlayground.triggered.connect(MainWindow.playground)
        self.actionReload_Settings_from_File.triggered.connect(MainWindow.reloadSettings)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SmallSmt Machine Server for OpenPnp"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.fnameLE.setText(_translate("MainWindow", "vp-calibration.json"))
        self.machineTypesCB.setItemText(0, _translate("MainWindow", "VP-2000S"))
        self.machineTypesCB.setItemText(1, _translate("MainWindow", "VP-2500DP"))
        self.machineTypesCB.setItemText(2, _translate("MainWindow", "VP-2500HP"))
        self.machineTypesCB.setItemText(3, _translate("MainWindow", "VP-2800HP"))
        self.label_3.setText(_translate("MainWindow", "Machine type"))
        self.selectConfgiPB.setText(_translate("MainWindow", "Select config file"))
        self.refreshPortPB.setText(_translate("MainWindow", "Refresh port"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTesting.setTitle(_translate("MainWindow", "Testing"))
        self.actionGlobal_settings.setText(_translate("MainWindow", "Edit global settings"))
        self.actionMachine_settings.setText(_translate("MainWindow", "Edit machine settings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save Settings"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save Settings"))
        self.actionPlayground.setText(_translate("MainWindow", "Playground"))
        self.actionReload_Settings_from_File.setText(_translate("MainWindow", "Reload Settings from File"))

